[package]
name = "habit_tracker_parser"
version = "0.1.3"
edition = "2021"
description = "A parser for habit tracking records"
license = "MIT"
readme = "README.md"


[dependencies]
anyhow = "1.0.93"
pest = "2.7.14"
pest_derive = "2.7.14"
thiserror = "2.0.0"
